# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.runs/synth_1/ICOBS_light_TOP.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.cache/wt [current_project]
set_property parent.project_path C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/demo-icobs-light.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/bootloader_icobs_light.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/ICOBS_light/COE/testcode_icobs_light.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/ICOBS_light/COE/demo-icobs-light.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/testcode_icobs_light.coe
add_files C:/Users/Gabriel/Downloads/testcode_icobs_light.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/car.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/kensei.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/knight.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/sorcerer.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/avatar.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/avatar_recontruted.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/blizzard.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/inferno.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/avatar_shot.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/avatar_shot_orange.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/winner.coe
add_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/COE/loser.coe
read_verilog C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/SHARED/prim_assert.sv
set_property file_type "Verilog Header" [get_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/SHARED/prim_assert.sv]
read_verilog -library xil_defaultlib -sv {
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_pkg.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_alu.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_compressed_decoder.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_controller.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_core.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_counter.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_cs_registers.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_decoder.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_ex_block.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_fetch_fifo.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_id_stage.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_if_stage.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_load_store_unit.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_multdiv_fast.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_prefetch_buffer.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_register_file_fpga.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX_CORE/ibex_wb_stage.sv
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/SHARED/prim_clock_gating.sv
}
read_vhdl -library interface C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/obi_lib.vhd
read_vhdl -library xil_defaultlib {
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/IBEX/IBEX.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/VGA/VGA_640_x_480.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/VGA/VGA_Basic_ROM.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/VGA/VGA_Mover_Top.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/VGA/VGA_clkdiv.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/AHBLITE/ahb_decoder_mcu.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/AHBLITE/ahblite_defaultslave.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/AHBLITE/ahblite_gpio.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/AHBLITE/ahblite_rstclk.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/AHBLITE/ahblite_timer.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/AHBLITE/ahblite_uart.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/VGA/ahblite_vga.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/clk_div.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/7SEG/clkdiv.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/7SEG/compteur.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/7SEG/gestion_an.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/7SEG/hex7seg.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/io_driver.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/MCU/mcu_interconnect.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/MCU/mcu_peripherals.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/7SEG/mux4x4.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/VGA/my_periph.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/obi_2_ram.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/obi_2_rom.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/obi_ahb_bridge.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/poweron_reset.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/7SEG/seg_top.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/MCU/top_mcu.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/ICOBS_light_TOP.vhd
}
read_vhdl -library common C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/LIB/constants.vhd
read_vhdl -library amba3 C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/LIB/amba3.vhd
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/arbiter.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/decoder.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/port_master.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/port_slave.vhd
  C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/RTL/OBI/xbar.vhd
}
read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/SPRAM_32x16384/SPRAM_32x16384.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/SPRAM_32x16384/SPRAM_32x16384_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/SPROM_32x1024/SPROM_32x1024.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/SPROM_32x1024/SPROM_32x1024_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/VGA_Clock_Multi/VGA_Clock_Multi.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/VGA_Clock_Multi/VGA_Clock_Multi_board.xdc]
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/VGA_Clock_Multi/VGA_Clock_Multi.xdc]
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/VGA_Clock_Multi/VGA_Clock_Multi_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/prom_sprite2/prom_sprite2.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/prom_sprite2/prom_sprite2_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/prom_sprite/prom_sprite.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/prom_sprite/prom_sprite_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/prom_sprite4/prom_sprite4.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/prom_sprite4/prom_sprite4_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/prom_sprite5/prom_sprite5.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/prom_sprite5/prom_sprite5_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/prom_sprite6/prom_sprite6.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/prom_sprite6/prom_sprite6_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/prom_sprite7/prom_sprite7.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/prom_sprite7/prom_sprite7_ooc.xdc]

read_ip -quiet C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/prom_sprite3/prom_sprite3.xci
set_property used_in_implementation false [get_files -all c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/prom_sprite3/prom_sprite3_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/FPGA/Basys3-Master.xdc
set_property used_in_implementation false [get_files C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light/FPGA/Basys3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/utils_1/imports/synth_1/ICOBS_light_TOP.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ICOBS_light_TOP -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ICOBS_light_TOP.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ICOBS_light_TOP_utilization_synth.rpt -pb ICOBS_light_TOP_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
