# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/SPROM_32x1024/SPROM_32x1024.xci
# IP: The module: 'SPROM_32x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/SPROM_32x1024/SPROM_32x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPROM_32x1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.srcs/sources_1/ip/SPROM_32x1024/SPROM_32x1024.xci
# IP: The module: 'SPROM_32x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/projets_polytech/VHDL_Icobs_Project/Hardware/ICOBS_light_PROJECT_DIR/ICOBS_light_PROJECT_DIR.gen/sources_1/ip/SPROM_32x1024/SPROM_32x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPROM_32x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
